# golangci-lint configuration
# Documentation: https://golangci-lint.run/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Go vet checks
    - ineffassign   # Detect unused variable assignments
    - staticcheck   # Static analysis checks
    - typecheck     # Type checking
    - unused        # Find unused code
    
    # Additional useful linters
    - gofmt         # Check gofmt formatting
    - goimports     # Check goimports formatting
    - misspell      # Find misspelled words
    - revive        # Fast linter replacement for golint
    - unconvert     # Remove unnecessary type conversions
    - whitespace    # Check for trailing whitespace

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true  # Allow packages without comments for now
      - name: var-naming
        disabled: false
      - name: indent-error-flow
        disabled: false
  
  gofmt:
    simplify: true
  
  misspell:
    locale: US

issues:
  # Disable default excludes to show all issues
  exclude-use-default: false
  
  # Maximum issues count per one linter. Set to 0 to disable the limit.
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text. Set to 0 to disable the limit.
  max-same-issues: 0
  
  # Exclude specific patterns
  exclude-rules:
    # Exclude test files from certain checks
    - path: _test\.go
      linters:
        - errcheck
        - revive