[tools]
node = "20"

# Development environment management tasks
[tasks.setup]
description = "Initialize TypeScript development environment"
run = """
    echo "🚀 Setting up ccstat TypeScript development environment..."
    echo "📋 Checking Node.js installation..."
    node --version
    npm --version
    echo "📦 Installing npm dependencies..."
    npm ci
    echo "🔧 Creating necessary directories..."
    mkdir -p dist bin
    echo "✅ Development environment setup complete!"
    echo ""
    echo "Next steps:"
    echo "  - Run 'npm run dev' for development mode"
    echo "  - Run 'npm run build' to build the project"
    echo "  - Run 'npm run test' to run tests"
    echo "  - Run 'npm run check' for quality checks"
"""

[tasks.deps]
description = "Install npm dependencies"
run = """
    echo "📦 Installing npm dependencies..."
    npm ci
    echo "✅ Dependencies installation complete"
"""

[tasks.lint]
description = "Run TypeScript linting"
run = "npm run lint"
sources = ["src/**/*.ts", "src/**/*.tsx", "package.json", "tsconfig.json"]

[tasks.format]
description = "Format TypeScript code"
run = """
    echo "🎨 Formatting TypeScript code..."
    npm run format
    echo "✅ Code formatting complete"
"""
sources = ["src/**/*.ts", "src/**/*.tsx"]

[tasks.dev]
description = "Development mode with file watching"
run = """
    echo "🔄 Starting TypeScript development mode..."
    echo "Watching for changes in TypeScript files..."
    echo "Press Ctrl+C to stop"
    echo ""
    mise watch --glob "src/**/*.ts" --glob "src/**/*.tsx" --glob "package.json" --glob "tsconfig.json" -- npm run dev
"""
sources = ["src/**/*.ts", "src/**/*.tsx", "package.json", "tsconfig.json"]

[tasks.build]
description = "Build the TypeScript project"
run = """
    echo "🔨 Building TypeScript project..."
    npm run build
    echo "✅ Build complete"
"""
sources = ["src/**/*.ts", "src/**/*.tsx", "package.json", "tsconfig.json"]

[tasks.test]
description = "Run tests"
run = """
    echo "🧪 Running tests..."
    npm run test
    echo "✅ Tests complete"
"""
sources = ["src/**/*.ts", "src/**/*.tsx", "src/**/*.test.ts"]

[tasks.check]
description = "Run all quality checks"
run = """
    echo "✅ Running all quality checks..."
    npm run check
    echo "✅ Quality checks complete"
"""
sources = ["src/**/*.ts", "src/**/*.tsx", "package.json", "tsconfig.json"]
