# GitHub Pages configuration for ccstat
# This ensures install.sh is served with the correct content type

plugins:
  - jekyll-redirect-from

# Ensure shell scripts are served with correct MIME type
defaults:
  - scope:
      path: "*.sh"
    values:
      layout: null